mongodb.connection_string=mongodb://ramim_admin:project106@ac-vapvm6k-shard-00-00.yxqie4w.mongodb.net:27017,ac-vapvm6k-shard-00-01.yxqie4w.mongodb.net:27017,ac-vapvm6k-shard-00-02.yxqie4w.mongodb.net:27017/?ssl=true&replicaSet=atlas-znz41r-shard-0&authSource=admin&appName=tuoxido
mongodb.database_name=LanMessengerDB
firebase.api_key=AIzaSyA3IhGPTegX-CQJk7HImN8SpNQeKZ2N0bY
imgbb.api_key=17693c9a056e83534dd33131bcd568c9