package com.lanmessenger;

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.ReplaceOptions;
import com.mongodb.client.model.Updates;
import org.bson.Document;
import org.bson.conversions.Bson;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

public class UserService {

    private static MongoCollection<Document> getUsersCollection() {
        MongoDatabase database = MongoDatabaseService.getDatabase();
        return database.getCollection("users");
    }

    private static MongoCollection<Document> getFriendRequestsCollection() {
        return MongoDatabaseService.getDatabase().getCollection("friend_requests");
    }

    private static MongoCollection<Document> getBlockedUsersCollection() {
        return MongoDatabaseService.getDatabase().getCollection("blocked_users");
    }

    // Match a relationship record regardless of sender and receiver order.
    private static Bson buildRelationshipFilter(String firstUsername, String secondUsername) {
        return Filters.or(
                Filters.and(Filters.eq("sender", firstUsername), Filters.eq("receiver", secondUsername)),
                Filters.and(Filters.eq("sender", secondUsername), Filters.eq("receiver", firstUsername))
        );
    }

    public static boolean isUsernameExists(String username) {
        MongoCollection<Document> usersCollection = getUsersCollection();
        Document foundUser = usersCollection.find(Filters.eq("username", username)).first();
        return foundUser != null;
    }

    public static boolean isUsernameTakenByOther(String newUsername, String currentEmail) {
        try {
            MongoCollection<Document> usersCollection = getUsersCollection();
            Document user = usersCollection.find(
                    Filters.and(
                            Filters.eq("username", newUsername),
                            Filters.ne("email", currentEmail)
                    )
            ).first();
            return user != null;
        } catch (Exception e) {
            return false;
        }
    }

    private static String generateRandomUsername(String name) {
        String baseName = name.replaceAll("\\s+", "").toLowerCase();
        int randomNum = new Random().nextInt(9000) + 1000;
        return baseName + "_" + randomNum;
    }

    public static String registerUser(String name, String email, String password) {
        try {
            MongoCollection<Document> usersCollection = getUsersCollection();

            String autoGeneratedUsername = generateRandomUsername(name);
            while (isUsernameExists(autoGeneratedUsername)) {
                autoGeneratedUsername = generateRandomUsername(name);
            }

            String defaultBirthday = "01/01/2026";

            Document newUser = new Document("name", name)
                    .append("email", email)
                    .append("username", autoGeneratedUsername)
                    .append("password", password)
                    .append("birthday", defaultBirthday)
                    .append("profilePic", "default_avatar.png")
                    .append("status", "offline");

            usersCollection.insertOne(newUser);
            System.out.println("✅ User Account Created in DB: " + autoGeneratedUsername);

            return autoGeneratedUsername;

        } catch (Exception e) {
            System.err.println("❌ Failed to create account: " + e.getMessage());
            return null;
        }
    }

    public static boolean updateProfileInfo(String email, String username, String name, String birthdate, String profilePic) {
        try {
            MongoCollection<org.bson.Document> users = getUsersCollection();

            com.mongodb.client.result.UpdateResult result = users.updateOne(
                    com.mongodb.client.model.Filters.eq("email", email),
                    com.mongodb.client.model.Updates.combine(
                            com.mongodb.client.model.Updates.set("username", username),
                            com.mongodb.client.model.Updates.set("name", name),
                            com.mongodb.client.model.Updates.set("birthdate", birthdate),
                            com.mongodb.client.model.Updates.set("birthday", birthdate),
                            com.mongodb.client.model.Updates.set("profilePic", profilePic)
                    )
            );
            return result.getMatchedCount() > 0;
        } catch (Exception e) {
            System.err.println("❌ Failed to update profile: " + e.getMessage());
            return false;
        }
    }

    public static List<Document> searchUsers(String searchQuery) {
        List<Document> results = new ArrayList<>();
        try {
            MongoCollection<Document> usersCollection = getUsersCollection();

            if (searchQuery == null || searchQuery.trim().isEmpty()) {
                return results;
            }

            Pattern namePattern = Pattern.compile(searchQuery, Pattern.CASE_INSENSITIVE);

            var filter = Filters.or(
                    Filters.eq("username", searchQuery.toLowerCase()),
                    Filters.regex("name", namePattern)
            );

            usersCollection.find(filter).limit(20).into(results);

        } catch (Exception e) {
            System.err.println("❌ Search error: " + e.getMessage());
        }
        return results;
    }

    public static boolean toggleArchive(String myUsername, String partnerUsername, boolean isArchive) {
        try {
            MongoCollection<Document> usersCollection = getUsersCollection();
            if (isArchive) {

                usersCollection.updateOne(Filters.eq("username", myUsername), Updates.addToSet("archivedChats", partnerUsername));
            } else {

                usersCollection.updateOne(Filters.eq("username", myUsername), Updates.pull("archivedChats", partnerUsername));
            }
            return true;
        } catch (Exception e) {
            System.err.println("Failed to toggle archive: " + e.getMessage());
            return false;
        }
    }

    public static List<String> getArchivedPartners(String myUsername) {
        List<String> archived = new ArrayList<>();
        try {
            Document user = getUsersCollection().find(Filters.eq("username", myUsername)).first();
            if (user != null && user.containsKey("archivedChats")) {
                archived = user.getList("archivedChats", String.class);
            }
        } catch (Exception e) {
            System.err.println("Failed to get archived chats: " + e.getMessage());
        }
        return archived;
    }

    public static Document getUserByUsername(String username) {
        try {
            return getUsersCollection().find(Filters.eq("username", username)).first();
        } catch (Exception e) {
            System.err.println("Error fetching user: " + e.getMessage());
            return null;
        }
    }

    public static Document getUserByEmail(String email) {
        try {
            return getUsersCollection().find(Filters.eq("email", email)).first();
        } catch (Exception e) {
            System.err.println("Error fetching user by email: " + e.getMessage());
            return null;
        }
    }

    public static UserProfile loadProfile(String localId, String email) {
        UserProfile cachedProfile = UserProfileStore.loadOrCreate(localId, email);

        if (email == null || email.isBlank()) {
            return cachedProfile;
        }

        try {
            Document user = getUserByEmail(email);
            if (user == null) {
                return cachedProfile;
            }

            String name = firstNonBlank(user.getString("name"), cachedProfile == null ? "" : cachedProfile.name);
            String username = firstNonBlank(user.getString("username"), cachedProfile == null ? "" : cachedProfile.username);
            String profilePic = firstNonBlank(user.getString("profilePic"), cachedProfile == null ? "default_avatar.png" : cachedProfile.profilePic);

            LocalDate birthdate = parseBirthdate(
                    firstNonBlank(user.getString("birthdate"), user.getString("birthday"))
            );
            if (birthdate == null && cachedProfile != null) {
                birthdate = cachedProfile.birthdate;
            }

            if (localId != null && !localId.isBlank()) {
                UserProfileStore.saveIdentity(localId, name, email);
                UserProfileStore.updateUsername(localId, username);
                UserProfileStore.updateBirthdate(localId, birthdate);
                UserProfileStore.updateProfilePic(localId, profilePic);
            }

            return new UserProfile(localId, name, email, username, birthdate, profilePic);
        } catch (Exception e) {
            System.err.println("Error loading profile: " + e.getMessage());
            return cachedProfile;
        }
    }

    public static UserProfile loadRequiredProfile(String localId, String email) {
        if (email == null || email.isBlank()) {
            return null;
        }

        try {
            Document user = getUserByEmail(email);
            if (user == null) {
                return null;
            }

            UserProfile cachedProfile = UserProfileStore.loadOrCreate(localId, email);
            String name = firstNonBlank(user.getString("name"), cachedProfile == null ? "" : cachedProfile.name);
            String username = firstNonBlank(user.getString("username"), cachedProfile == null ? "" : cachedProfile.username);
            String profilePic = firstNonBlank(user.getString("profilePic"), cachedProfile == null ? "default_avatar.png" : cachedProfile.profilePic);

            LocalDate birthdate = parseBirthdate(
                    firstNonBlank(user.getString("birthdate"), user.getString("birthday"))
            );
            if (birthdate == null && cachedProfile != null) {
                birthdate = cachedProfile.birthdate;
            }

            if (localId != null && !localId.isBlank()) {
                UserProfileStore.saveIdentity(localId, name, email);
                UserProfileStore.updateUsername(localId, username);
                UserProfileStore.updateBirthdate(localId, birthdate);
                UserProfileStore.updateProfilePic(localId, profilePic);
            }

            return new UserProfile(localId, name, email, username, birthdate, profilePic);
        } catch (Exception e) {
            System.err.println("Error loading required profile: " + e.getMessage());
            return null;
        }
    }

    public static java.util.List<org.bson.Document> searchFriendsByQuery(String searchQuery, String myUsername) {
        java.util.List<org.bson.Document> results = new java.util.ArrayList<>();
        try {
            com.mongodb.client.MongoCollection<org.bson.Document> usersCollection = getUsersCollection();
            com.mongodb.client.MongoCollection<org.bson.Document> reqCol = getFriendRequestsCollection();

            if (searchQuery == null || searchQuery.trim().isEmpty()) return results;

            java.util.regex.Pattern namePattern = java.util.regex.Pattern.compile(searchQuery, java.util.regex.Pattern.CASE_INSENSITIVE);
            var filter = com.mongodb.client.model.Filters.or(
                    com.mongodb.client.model.Filters.eq("username", searchQuery.toLowerCase()),
                    com.mongodb.client.model.Filters.regex("name", namePattern)
            );

            for (org.bson.Document doc : usersCollection.find(filter).limit(20)) {
                String targetUsername = doc.getString("username");
                if (!targetUsername.equals(myUsername) && !isBlocked(myUsername, targetUsername)) {
                    org.bson.conversions.Bson reqFilter = buildRelationshipFilter(myUsername, targetUsername);
                    org.bson.Document req = reqCol.find(reqFilter).sort(new org.bson.Document("timestamp", -1)).first();
                    String status = (req != null) ? req.getString("status") : "none";

                    org.bson.Document safeDoc = new org.bson.Document();
                    safeDoc.putAll(doc);
                    safeDoc.put("friendshipStatus", status);
                    results.add(safeDoc);
                }
            }
        } catch (Exception e) { e.printStackTrace(); }
        return results;
    }

    private static String firstNonBlank(String primary, String fallback) {
        if (primary != null && !primary.isBlank()) {
            return primary;
        }
        return fallback == null ? "" : fallback;
    }

    private static LocalDate parseBirthdate(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }

        try {
            return LocalDate.parse(value);
        } catch (Exception ignored) {
        }

        try {
            return LocalDate.parse(value, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } catch (Exception ignored) {
        }

        return null;
    }

    public static boolean sendFriendRequest(String senderUsername, String receiverUsername) {
        try {
            if (isBlocked(senderUsername, receiverUsername)) {
                return false;
            }

            com.mongodb.client.MongoCollection<org.bson.Document> requestsCol = getFriendRequestsCollection();

            org.bson.conversions.Bson filter = buildRelationshipFilter(senderUsername, receiverUsername);

            org.bson.Document existingReq = requestsCol.find(filter).first();
            if (existingReq != null) {
                return false;
            }

            org.bson.Document newReq = new org.bson.Document("sender", senderUsername)
                    .append("receiver", receiverUsername)
                    .append("status", "pending")
                    .append("timestamp", System.currentTimeMillis());

            requestsCol.insertOne(newReq);
            return true;
        } catch (Exception e) {
            System.err.println("❌ Error sending friend request: " + e.getMessage());
            return false;
        }
    }

    public static java.util.List<org.bson.Document> getPendingRequests(String myUsername) {
        java.util.List<org.bson.Document> requests = new java.util.ArrayList<>();
        try {
            com.mongodb.client.MongoCollection<org.bson.Document> reqCol = getFriendRequestsCollection();
            reqCol.find(com.mongodb.client.model.Filters.and(
                    com.mongodb.client.model.Filters.eq("receiver", myUsername),
                    com.mongodb.client.model.Filters.eq("status", "pending")
            )).into(requests);
        } catch (Exception e) {
            System.err.println("❌ Error fetching requests: " + e.getMessage());
        }
        return requests;
    }

    public static boolean respondToRequest(String sender, String receiver, boolean accept) {
        try {
            if (isBlocked(sender, receiver)) {
                getFriendRequestsCollection().deleteMany(buildRelationshipFilter(sender, receiver));
                return false;
            }

            com.mongodb.client.MongoCollection<org.bson.Document> reqCol = getFriendRequestsCollection();
            org.bson.conversions.Bson filter = com.mongodb.client.model.Filters.and(
                    com.mongodb.client.model.Filters.eq("sender", sender),
                    com.mongodb.client.model.Filters.eq("receiver", receiver)
            );

            if (accept) {
                reqCol.updateOne(filter, com.mongodb.client.model.Updates.set("status", "accepted"));
            } else {
                reqCol.deleteOne(filter);
            }
            return true;
        } catch (Exception e) {
            System.err.println("❌ Error responding to request: " + e.getMessage());
            return false;
        }
    }

    public static java.util.List<org.bson.Document> getMyFriendsList(String myUsername) {
        java.util.List<org.bson.Document> friends = new java.util.ArrayList<>();
        try {
            com.mongodb.client.MongoCollection<org.bson.Document> reqCol = getFriendRequestsCollection();

            org.bson.conversions.Bson filter = com.mongodb.client.model.Filters.and(
                    com.mongodb.client.model.Filters.eq("status", "accepted"),
                    com.mongodb.client.model.Filters.or(
                            com.mongodb.client.model.Filters.eq("sender", myUsername),
                            com.mongodb.client.model.Filters.eq("receiver", myUsername)
                    )
            );

            reqCol.find(filter).forEach(doc -> {
                String friendUsername = doc.getString("sender").equals(myUsername) ? doc.getString("receiver") : doc.getString("sender");
                if (isBlocked(myUsername, friendUsername)) {
                    return;
                }
                org.bson.Document userDoc = getUserByUsername(friendUsername);
                if (userDoc != null) friends.add(userDoc);
            });
        } catch (Exception e) {
            System.err.println("❌ Error fetching friends: " + e.getMessage());
        }
        return friends;
    }

    public static boolean removeFriend(String myUsername, String friendUsername) {
        try {
            com.mongodb.client.MongoCollection<org.bson.Document> reqCol = getFriendRequestsCollection();
            org.bson.conversions.Bson filter = buildRelationshipFilter(myUsername, friendUsername);
            reqCol.deleteMany(filter);
            return true;
        } catch (Exception e) { return false; }
    }

    public static boolean blockUser(String myUsername, String blockedUsername) {
        try {

            removeFriend(myUsername, blockedUsername);

            com.mongodb.client.MongoCollection<org.bson.Document> blockCol = getBlockedUsersCollection();
            blockCol.deleteMany(com.mongodb.client.model.Filters.and(
                    com.mongodb.client.model.Filters.eq("blocker", myUsername),
                    com.mongodb.client.model.Filters.eq("blocked", blockedUsername)
            ));

            org.bson.Document blockDoc = new org.bson.Document("blocker", myUsername)
                    .append("blocked", blockedUsername)
                    .append("timestamp", System.currentTimeMillis());
            blockCol.replaceOne(
                    com.mongodb.client.model.Filters.and(
                            com.mongodb.client.model.Filters.eq("blocker", myUsername),
                            com.mongodb.client.model.Filters.eq("blocked", blockedUsername)
                    ),
                    blockDoc,
                    new ReplaceOptions().upsert(true)
            );
            return true;
        } catch (Exception e) { return false; }
    }

    public static boolean isBlocked(String userA, String userB) {
        try {
            return isBlockedBy(userA, userB) || isBlockedBy(userB, userA);
        } catch (Exception e) { return false; }
    }

    public static boolean isBlockedBy(String blockerUsername, String blockedUsername) {
        if (blockerUsername == null || blockedUsername == null
                || blockerUsername.isBlank() || blockedUsername.isBlank()) {
            return false;
        }
        try {
            com.mongodb.client.MongoCollection<org.bson.Document> blockCol = getBlockedUsersCollection();
            org.bson.conversions.Bson filter = com.mongodb.client.model.Filters.and(
                    com.mongodb.client.model.Filters.eq("blocker", blockerUsername),
                    com.mongodb.client.model.Filters.eq("blocked", blockedUsername)
            );
            return blockCol.find(filter).first() != null;
        } catch (Exception e) {
            return false;
        }
    }

    public static java.util.List<String> getBlockedUsersList(String myUsername) {
        java.util.List<String> blockedList = new java.util.ArrayList<>();
        try {
            java.util.Set<String> uniqueBlocked = new java.util.LinkedHashSet<>();
            com.mongodb.client.MongoCollection<org.bson.Document> blockCol = getBlockedUsersCollection();

            blockCol.find(com.mongodb.client.model.Filters.eq("blocker", myUsername)).forEach(doc -> {
                uniqueBlocked.add(doc.getString("blocked"));
            });
            blockedList.addAll(uniqueBlocked);
        } catch (Exception e) { e.printStackTrace(); }
        return blockedList;
    }

    public static boolean unblockUser(String myUsername, String blockedUsername) {
        try {
            com.mongodb.client.MongoCollection<org.bson.Document> blockCol = getBlockedUsersCollection();
            blockCol.deleteMany(com.mongodb.client.model.Filters.and(
                    com.mongodb.client.model.Filters.eq("blocker", myUsername),
                    com.mongodb.client.model.Filters.eq("blocked", blockedUsername)
            ));
            return true;
        } catch (Exception e) { return false; }
    }

    // Keep related collections aligned after a username change.
    public static void migrateUserData(String oldUsername, String newUsername) {
        try {
            com.mongodb.client.MongoDatabase db = MongoDatabaseService.getDatabase();

            db.getCollection("messages").updateMany(Filters.eq("sender", oldUsername), Updates.set("sender", newUsername));
            db.getCollection("messages").updateMany(Filters.eq("receiver", oldUsername), Updates.set("receiver", newUsername));
            db.getCollection("messages").updateMany(
                    Filters.in("readBy", oldUsername),
                    Updates.set("readBy.$[elem]", newUsername),
                    new com.mongodb.client.model.UpdateOptions().arrayFilters(
                            java.util.List.of(Filters.eq("elem", oldUsername))
                    )
            );

            db.getCollection("moments").updateMany(Filters.eq("username", oldUsername), Updates.set("username", newUsername));

            db.getCollection("groups").updateMany(Filters.eq("creator", oldUsername), Updates.set("creator", newUsername));
            db.getCollection("groups").updateMany(
                    Filters.in("members", oldUsername),
                    Updates.set("members.$[elem]", newUsername),
                    new com.mongodb.client.model.UpdateOptions().arrayFilters(
                            java.util.List.of(Filters.eq("elem", oldUsername))
                    )
            );

            db.getCollection("friend_requests").updateMany(Filters.eq("sender", oldUsername), Updates.set("sender", newUsername));
            db.getCollection("friend_requests").updateMany(Filters.eq("receiver", oldUsername), Updates.set("receiver", newUsername));

            db.getCollection("blocked_users").updateMany(Filters.eq("blocker", oldUsername), Updates.set("blocker", newUsername));
            db.getCollection("blocked_users").updateMany(Filters.eq("blocked", oldUsername), Updates.set("blocked", newUsername));

            System.out.println("✅ All data perfectly migrated: " + oldUsername + " -> " + newUsername);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
